"""C 与 C++ 共享的版本化安全规则包。"""

from .standard_library import C_FAMILY_SQLITE_PACK, C_FAMILY_STANDARD_LIBRARY_PACK

C_FAMILY_RULE_PACKS = (C_FAMILY_STANDARD_LIBRARY_PACK, C_FAMILY_SQLITE_PACK)

__all__ = ["C_FAMILY_RULE_PACKS"]
