"""JS/TS 平台和 Express 规则：结构候选不等同于可利用漏洞。"""

from .base import AccessRule, CallCondition, CallRule, EntrypointRule, RulePack

_LANGUAGES = ("javascript", "typescript")
_CONTROL = (
    "必须验证攻击者能控制相应输入；环境配置由可信部署人员设置时不能据此认定远程漏洞。",
)

JAVASCRIPT_RULE_PACKS = (
    RulePack(
        name="javascript-typescript-core",
        version="1.2",
        languages=_LANGUAGES,
        entrypoint_rules=(
            EntrypointRule(
                "JS-NODE-HTTP-SERVER",
                "node:http",
                _LANGUAGES,
                registration_call_methods=(
                    ("http.createServer", "all"),
                    ("https.createServer", "all"),
                ),
                registration_path_position=-1,
                registration_handler_position=-1,
                source_parameter_positions=(),
            ),
            EntrypointRule(
                rule_id="JS-EXPRESS-ROUTE",
                framework="express",
                languages=_LANGUAGES,
                registration_call_methods=tuple(
                    (f"express.Application.{method}", method)
                    for method in (
                        "get",
                        "post",
                        "put",
                        "patch",
                        "delete",
                        "head",
                        "options",
                        "all",
                    )
                ),
                source_parameter_positions=(),  # req/res/next 不是三个外部标量输入。
            ),
        ),
        access_rules=(
            AccessRule(
                "JS-SOURCE-VUE-MODEL", "source", "browser_input",
                ("vue.template.v-model",), languages=_LANGUAGES,
                trust_class="untrusted", result_role="source",
                preconditions=("仅 script setup 原生文本输入的可写变量或显式 Vue ref；事件可能未发生，修饰符不视为安全净化。",),
            ),
            AccessRule(
                "JS-SOURCE-INPUT-EVENT", "source", "browser_input",
                ("react.DOM.InputEvent.target.value", "react.DOM.InputEvent.currentTarget.value"),
                languages=_LANGUAGES, trust_class="untrusted", result_role="source",
                preconditions=("已确认原生表单事件注册；仍须验证攻击者影响、传播与实际输出上下文。",),
            ),
            AccessRule(
                "JS-SOURCE-NODE-BODY", "source", "http_body",
                ("node.IncomingMessage.bodyChunk",),
                languages=_LANGUAGES, trust_class="untrusted", result_role="source",
                preconditions=("仅注册 data 回调的首个形参；未建模跨回调累积、end 时序或 Buffer 解码边界。",),
            ),
            AccessRule(
                "JS-SOURCE-ARGV",
                "source",
                "cli_argument",
                ("process.argv",),
                languages=_LANGUAGES,
                trust_class="unknown",
                result_role="source",
                preconditions=_CONTROL,
            ),
            AccessRule(
                "JS-SOURCE-NODE-HTTP",
                "source",
                "http_parameter",
                ("node.IncomingMessage.url", "node.IncomingMessage.headers"),
                languages=_LANGUAGES,
                trust_class="untrusted",
                result_role="source",
            ),
            AccessRule(
                "JS-SOURCE-REACT-PROPS",
                "source",
                "component_property",
                ("react.Component.props",),
                languages=_LANGUAGES,
                trust_class="unknown",
                result_role="source",
                preconditions=(
                    "组件 props 并非天然攻击者输入，必须核实父组件、SSR 或外部数据来源。",
                ),
            ),
            AccessRule(
                "JS-SINK-REACT-HTML",
                "sink",
                "html_injection",
                ("react.DOM.dangerouslySetInnerHTML",),
                access_kinds=("write",),
                languages=_LANGUAGES,
                cwe="CWE-79",
                severity="high",
                argument_role="sink",
                preconditions=(
                    "必须确认 React 原生 DOM 渲染上下文与 __html 字段可控性；普通 JSX children 不属于此 Sink。",
                ),
            ),
            AccessRule(
                "JS-SINK-VUE-HTML",
                "sink",
                "html_injection",
                ("vue.template.v-html", "vue.render.innerHTML"),
                access_kinds=("write",),
                languages=_LANGUAGES,
                cwe="CWE-79",
                severity="high",
                argument_role="sink",
                preconditions=(
                    "必须确认原始 HTML 可控与输出上下文；普通模板插值不属于此 Sink。",
                ),
            ),
            AccessRule(
                "JS-SOURCE-BROWSER",
                "source",
                "browser_input",
                (
                    "location.search",
                    "location.hash",
                    "location.href",
                    "document.cookie",
                ),
                languages=_LANGUAGES,
                trust_class="untrusted",
                result_role="source",
            ),
            AccessRule(
                "JS-SOURCE-HTTP",
                "source",
                "http_parameter",
                tuple(
                    f"express.Request.{part}"
                    for part in ("query", "body", "params", "headers", "cookies")
                ),
                languages=_LANGUAGES,
                trust_class="untrusted",
                result_role="source",
            ),
            AccessRule(
                "JS-SOURCE-ENV",
                "source",
                "environment_input",
                ("process.env",),
                languages=_LANGUAGES,
                trust_class="external_configuration",
                result_role="source",
                preconditions=_CONTROL,
            ),
            AccessRule(
                "JS-SINK-DOM",
                "sink",
                "html_injection",
                (
                    "DOM.Element.innerHTML",
                    "DOM.Element.outerHTML",
                    "DOM.Element.srcdoc",
                ),
                access_kinds=("write",),
                languages=_LANGUAGES,
                cwe="CWE-79",
                severity="high",
                argument_role="sink",
                preconditions=(
                    "必须确认写入值含可执行的攻击者 HTML，并考虑实际 DOM 上下文、净化器和 Trusted Types 策略。",
                ),
            ),
        ),
        call_rules=(
            CallRule(
                "JS-SOURCE-VUE-PROPS",
                "source",
                "component_property",
                ("vue.defineProps",),
                languages=_LANGUAGES,
                trust_class="unknown",
                result_role="source",
                preconditions=(
                    "Vue props 是否不可信取决于父组件或外部数据，不可仅凭 defineProps 判断漏洞。",
                ),
            ),
            CallRule(
                "JS-SOURCE-STORAGE",
                "source",
                "browser_storage",
                ("localStorage.getItem", "sessionStorage.getItem"),
                languages=_LANGUAGES,
                trust_class="unknown",
                result_role="source",
                preconditions=(
                    "浏览器存储不是天然外部输入，需确认攻击者可以影响该键对应的数据。",
                ),
            ),
            CallRule(
                "JS-SOURCE-FILE",
                "source",
                "external_file",
                ("fs.readFileSync", "fs.promises.readFile"),
                languages=_LANGUAGES,
                trust_class="external_file",
                result_role="source",
            ),
            CallRule(
                "JS-SINK-SHELL",
                "sink",
                "shell_execution",
                ("child_process.exec", "child_process.execSync"),
                languages=_LANGUAGES,
                cwe="CWE-78",
                severity="high",
                argument_role="sink",
                argument_positions=(0,),
                implicit_shell=True,
                preconditions=_CONTROL,
            ),
            CallRule(
                "JS-SINK-SHELL-OPTION",
                "sink",
                "shell_execution",
                (
                    "child_process.execFile",
                    "child_process.execFileSync",
                    "child_process.spawn",
                    "child_process.spawnSync",
                ),
                languages=_LANGUAGES,
                cwe="CWE-78",
                severity="high",
                argument_role="sink",
                argument_positions=(0, 1),
                implicit_shell=True,
                conditions=(CallCondition("equals", (True,), keyword="shell"),),
                preconditions=_CONTROL,
            ),
            CallRule(
                "JS-SINK-PROCESS",
                "sink",
                "process_execution",
                (
                    "child_process.execFile",
                    "child_process.execFileSync",
                    "child_process.spawn",
                    "child_process.spawnSync",
                ),
                languages=_LANGUAGES,
                cwe="CWE-78",
                severity="medium",
                argument_role="sink",
                argument_positions=(0,),
                implicit_shell=False,
                conditions=(
                    CallCondition(
                        "equals",
                        (False,),
                        keyword="shell",
                        has_default=True,
                        default=False,
                    ),
                ),
                preconditions=(
                    "仅检查可控可执行文件路径；默认无 Shell，不把普通命令参数认定为 Shell 注入。",
                ),
            ),
            CallRule(
                "JS-SINK-EVAL",
                "sink",
                "dynamic_code_execution",
                ("eval", "Function"),
                languages=_LANGUAGES,
                cwe="CWE-95",
                severity="high",
                argument_role="sink",
                argument_positions=(0,),
            ),
            CallRule(
                "JS-SINK-DOM-CALL",
                "sink",
                "html_injection",
                ("document.write", "document.writeln"),
                languages=_LANGUAGES,
                cwe="CWE-79",
                severity="high",
                argument_role="sink",
                argument_positions=(0,),
            ),
            CallRule(
                "JS-SINK-ADJACENT-HTML",
                "sink",
                "html_injection",
                ("DOM.Element.insertAdjacentHTML",),
                languages=_LANGUAGES,
                cwe="CWE-79",
                severity="high",
                argument_role="sink",
                argument_positions=(1,),
            ),
            CallRule(
                "JS-SINK-FILE",
                "sink",
                "file_path",
                tuple(
                    f"fs.{name}"
                    for name in (
                        "readFileSync",
                        "writeFileSync",
                        "readFile",
                        "writeFile",
                        "unlink",
                        "unlinkSync",
                        "createReadStream",
                        "createWriteStream",
                        "promises.readFile",
                        "promises.writeFile",
                        "promises.unlink",
                    )
                ),
                languages=_LANGUAGES,
                cwe="CWE-22",
                severity="medium",
                argument_role="sink",
                argument_positions=(0,),
                preconditions=(
                    "必须验证路径越出允许目录且攻击者可控；正常可信文件访问不是漏洞。",
                ),
            ),
            CallRule(
                "JS-SINK-NETWORK",
                "sink",
                "network_request",
                (
                    "fetch",
                    "http.get",
                    "http.request",
                    "https.get",
                    "https.request",
                    "axios",
                    "axios.get",
                    "axios.post",
                ),
                languages=_LANGUAGES,
                cwe="CWE-918",
                severity="medium",
                argument_role="sink",
                argument_positions=(0,),
                preconditions=(
                    "仅服务端可控目标请求可能构成 SSRF；浏览器 fetch 不等同服务端 SSRF，需核实运行环境和目标限制。",
                ),
            ),
            CallRule(
                "JS-SANITIZER-HTML",
                "sanitizer",
                "html_sanitizer",
                ("dompurify.sanitize",),
                languages=_LANGUAGES,
                argument_role="sanitizer_input",
                argument_positions=(0,),
                preconditions=(
                    "净化有效性取决于配置与输出上下文；未进行上下文匹配前不得自动删除候选路径。",
                ),
            ),
        ),
    ),
)
